Repository canonical/craft-parts, pull requests merged in 2024-09, with the labels that each got.

#845 fix(plugins): ensure stateless npm plugin
  craft_parts/plugins/npm_plugin.py
  tests/unit/plugins/test_npm_plugin.py
Labels: squash

#847 Release 1.33.1
  .bumpversion.cfg
  craft_parts/__init__.py
  docs/changelog.rst
  setup.py
Labels: rebase

#848 chore(merge): 'merge-1.33.1' into 'main'
  craft_parts/plugins/npm_plugin.py
  docs/changelog.rst
  tests/unit/plugins/test_npm_plugin.py
Labels: merge

#850 docs(rust_plugin): update explanations to reflect changes in newer Rust toolchains
  docs/common/craft-parts/craft-parts.wordlist.txt
  docs/common/craft-parts/reference/plugins/rust_plugin.rst
Labels: Documentation, squash
