Repository canonical/craft-parts, pull requests merged in 2024-12, with the labels that each got.

#923 chore(merge): 2.1.4 into main
  .bumpversion.cfg
  craft_parts/__init__.py
  craft_parts/executor/environment.py
  craft_parts/infos.py
  craft_parts/plugins/poetry_plugin.py
  docs/changelog.rst
  pyproject.toml
  setup.py
  tests/unit/plugins/test_poetry_plugin.py
  tests/unit/test_infos.py
Labels: merge

#916 doc(ant,maven): add labels for description
  docs/common/craft-parts/reference/plugins/ant_plugin.rst
  docs/common/craft-parts/reference/plugins/maven_plugin.rst
Labels: squash

#913 link to common part properties
  docs/common/craft-parts/reference/plugins/npm_plugin.rst
Labels: squash

#931 feat: npm plugin file listing
  .github/workflows/tests.yaml
  Makefile
  craft_parts/plugins/base.py
  craft_parts/plugins/npm_plugin.py
  docs/common/craft-parts/craft-parts.wordlist.txt
  pyproject.toml
  tests/integration/plugins/test_npm.py
  tests/unit/plugins/test_npm_plugin.py
Labels: squash

#942 docs: move changelog, add PR task
  .github/PULL_REQUEST_TEMPLATE.md
  docs/reference/changelog.rst
  docs/reference/index.rst
Labels: rebase

#941 docs(changelog): add 2.2.0 changes
  docs/common/craft-parts/craft-parts.wordlist.txt
  docs/reference/changelog.rst
Labels: squash
