Repository canonical/craft-parts, pull requests merged in 2025-01, with the labels that each got.

#953 chore(merge): 1.25.3 into main
  docs/reference/changelog.rst
Labels: merge

#949 docs: update and complete the step execution environment
  docs/common/craft-parts/craft-parts.wordlist.txt
  docs/common/craft-parts/reference/step_execution_environment.rst
  docs/reference/changelog.rst
Labels: Documentation

#951 feat: implement Jlink plugin
  .github/workflows/tests.yaml
  craft_parts/plugins/jlink_plugin.py
  craft_parts/plugins/plugins.py
  craft_parts/sources/__init__.py
  docs/common/craft-parts/craft-parts.wordlist.txt
  docs/common/craft-parts/reference/plugins/jlink_plugin.rst
  docs/reference/changelog.rst
  docs/reference/plugins.rst
  tests/integration/plugins/test_jlink.py
  tests/unit/plugins/test_jlink_plugin.py
Labels: squash
